### ISSUE TITLE
login function for backend returning "user not found" if it can find a user of the username entered in the frontend, and returning "server error" if it cant

### ISSUE THREAD

**Issue by Jayd-H** [Jayd-H/UniSphere#71]
this is irrespective of if the password is right, i think the login function needs a rewrite to be honest

**Comment by BallerHat** [comment]
When testing locally I couldn't reproduce the "user not found" bug. And with "server error", I could only reproduce that when using HTTPS instead of HTTP to access the API. Could this be an issue with how the solution has been set up/hosted?

**Comment by Jayd-H** [comment]
I have no clue I just noticed it when using the vercel deployment.

https://unispher-e.vercel.app/login

When entering a username that exists in the database (eg. 'testt'), regardless of if the password is correct or not, the error message that gets sent back to frontend and displayed on the form is "user not found". If you enter in a username that does not exist on the database the error displayed is "server error". I do not understand why, you will most likely be more familiar with this kind of logic, I have never messed with express js servers before.

Note that this does not affect the function for registration, as that uses very similar logic to check if the username the user entered already exists in the database before proceeding with registration. It is strange that the register function works completely as expected but login does not.

**Comment by BallerHat** [comment]
When posting directly to the API, I now see the "User not found" issue, but given that I don't see the same response on a local deployment I think the issue may lie with Vercel? I'm not really familiar with Vercel and I don't think I have access to test, so correct me if I'm wrong.
![Posting login to the API](https://github.com/Jayd-H/UniSphere/assets/46404288/1282fcf7-bcf0-43f1-9a55-2a9846e0800c)
![Posting login to local API](https://github.com/Jayd-H/UniSphere/assets/46404288/6303a82f-b068-4ca2-8aee-6fc7f34a71b6)

**Comment by Jayd-H** [comment]
That is strange, I will look into it thank youuuu

**Comment by BallerHat** [comment]
A little while back, Sam made some changes to the database schema in the backend and has updated Azure to reflect this. Has the backend on Vercel hasn't been updated to that point?

**Comment by Jayd-H** [comment]
I am pretty sure him and I changed it to reflect that but you are free to double check as you are most likely a lot more knowledgeable than both of us when it comes to this stuff. You can connect to the database with MySQL workbench with the details in the discord and cross-reference it yourself. Currently I am trying to reproduce your success but with my verbose error messages to see what the culprit is.

**Comment by Jayd-H** [comment]
I can confirm that it works locally, so it must be an issue with vercel. womp womp

**Comment by Jayd-H** [comment]
It seems like I updated the vercel node version from 18 to 20, the only difference I could find between vercel and running locally, and it seems to have fixed it. My bad for this one guys.

![image](https://github.com/Jayd-H/UniSphere/assets/70723772/c654e6ba-afde-4316-82ee-081975aba297)
